# This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 05/27/2016

module MarvelComics
  class Configuration
    # The base Uri for API calls
    @base_uri = 'http://gateway.marvel.com/v1/public'

    @referer = 'TODO: Replace'

    @apikey = 'TODO: Replace'

    # create the getters and setters
    class << self
      attr_accessor :base_uri
      attr_accessor :referer
      attr_accessor :apikey
    end
  end
end
