# This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 05/27/2016

module MarvelComics
  class MarvelComicsClient
    # Singleton access to characters controller
    # @return [CharactersController] Returns the controller instance
    def characters
      CharactersController.instance
    end

    # Singleton access to comics controller
    # @return [ComicsController] Returns the controller instance
    def comics
      ComicsController.instance
    end

    # Singleton access to creators controller
    # @return [CreatorsController] Returns the controller instance
    def creators
      CreatorsController.instance
    end

    # Singleton access to events controller
    # @return [EventsController] Returns the controller instance
    def events
      EventsController.instance
    end

    # Singleton access to series controller
    # @return [SeriesController] Returns the controller instance
    def series
      SeriesController.instance
    end

    # Singleton access to stories controller
    # @return [StoriesController] Returns the controller instance
    def stories
      StoriesController.instance
    end

    # Initializer with authentication and configuration parameters
    def initialize(referer: nil, apikey: nil)
      Configuration.referer = referer
      Configuration.apikey = apikey
    end
  end
end
