# This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 05/27/2016

module MarvelComics
  class CharacterSummary

    # The path to the individual character resource.
    # @return [String]
    attr_accessor :resource_uri

    # The full name of the character.
    # @return [String]
    attr_accessor :name

    # The role of the creator in the parent entity.
    # @return [String]
    attr_accessor :role

    def initialize(resource_uri = nil,
                   name = nil,
                   role = nil)
      @resource_uri = resource_uri
      @name = name
      @role = role

    end

    def method_missing(method_name)
      puts "There is no method called '#{method_name}'."
    end

    # Creates JSON of the curent object
    def to_json(options = {})
      hash = key_map
      hash.to_json(options)
    end

    # Creates an instance of the object from a hash
    def self.from_hash(hash)
      if hash == nil
        nil
      else
        # Extract variables from the hash
        resource_uri = hash["resourceURI"]
        name = hash["name"]
        role = hash["role"]
        # Create object from extracted values
        CharacterSummary.new(resource_uri,
                             name,
                             role)
      end
    end

    # Defines the key map for json serialization
    def key_map
      hash = {}
      hash['resourceURI'] = resource_uri
      hash['name'] = name
      hash['role'] = role
      hash
    end
  end
end
