# This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 05/27/2016

module MarvelComics
  class ComicPrice

    # A description of the price (e.g. print price, digital price).
    # @return [String]
    attr_accessor :type

    # The price (all prices in USD).
    # @return [Float]
    attr_accessor :price

    def initialize(type = nil,
                   price = nil)
      @type = type
      @price = price

    end

    def method_missing(method_name)
      puts "There is no method called '#{method_name}'."
    end

    # Creates JSON of the curent object
    def to_json(options = {})
      hash = key_map
      hash.to_json(options)
    end

    # Creates an instance of the object from a hash
    def self.from_hash(hash)
      if hash == nil
        nil
      else
        # Extract variables from the hash
        type = hash["type"]
        price = hash["price"]
        # Create object from extracted values
        ComicPrice.new(type,
                       price)
      end
    end

    # Defines the key map for json serialization
    def key_map
      hash = {}
      hash['type'] = type
      hash['price'] = price
      hash
    end
  end
end
