# This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 05/27/2016

require 'date'
module MarvelComics
  class Creator

    # The unique ID of the creator resource.
    # @return [Integer]
    attr_accessor :id

    # The first name of the creator.
    # @return [String]
    attr_accessor :first_name

    # The middle name of the creator.
    # @return [String]
    attr_accessor :middle_name

    # The last name of the creator.
    # @return [String]
    attr_accessor :last_name

    # The suffix or honorific for the creator.
    # @return [String]
    attr_accessor :suffix

    # The full name of the creator (a space-separated concatenation of the above four fields).
    # @return [String]
    attr_accessor :full_name

    # The date the resource was most recently modified.
    # @return [DateTime]
    attr_accessor :modified

    # The canonical URL identifier for this resource.
    # @return [String]
    attr_accessor :resource_uri

    # A set of public web site URLs for the resource.
    # @return [List of UrlModel]
    attr_accessor :urls

    # The representative image for this creator.
    # @return [Thumbnail]
    attr_accessor :thumbnail

    # A resource list containing the series which feature work by this creator.
    # @return [SeriesList]
    attr_accessor :series

    # A resource list containing the stories which feature work by this creator.
    # @return [StoryList]
    attr_accessor :stories

    # A resource list containing the comics which feature work by this creator.
    # @return [ComicList]
    attr_accessor :comics

    # A resource list containing the events which feature work by this creator.
    # @return [EventList]
    attr_accessor :events

    def initialize(id = nil,
                   first_name = nil,
                   middle_name = nil,
                   last_name = nil,
                   suffix = nil,
                   full_name = nil,
                   modified = nil,
                   resource_uri = nil,
                   urls = nil,
                   thumbnail = nil,
                   series = nil,
                   stories = nil,
                   comics = nil,
                   events = nil)
      @id = id
      @first_name = first_name
      @middle_name = middle_name
      @last_name = last_name
      @suffix = suffix
      @full_name = full_name
      @modified = modified
      @resource_uri = resource_uri
      @urls = urls
      @thumbnail = thumbnail
      @series = series
      @stories = stories
      @comics = comics
      @events = events

    end

    def method_missing(method_name)
      puts "There is no method called '#{method_name}'."
    end

    # Creates JSON of the curent object
    def to_json(options = {})
      hash = key_map
      hash.to_json(options)
    end

    # Creates an instance of the object from a hash
    def self.from_hash(hash)
      if hash == nil
        nil
      else
        # Extract variables from the hash
        id = hash["id"]
        first_name = hash["firstName"]
        middle_name = hash["middleName"]
        last_name = hash["lastName"]
        suffix = hash["suffix"]
        full_name = hash["fullName"]
        modified = DateTime.iso8601(hash["modified"])
        resource_uri = hash["resourceURI"]
        # Parameter is an array, so we need to iterate through it
        urls = nil
        if hash["urls"] != nil
          urls = Array.new
          hash["urls"].each{|structure| urls << UrlModel.from_hash(structure)}
        end
        thumbnail = Thumbnail.from_hash(hash["thumbnail"])
        series = SeriesList.from_hash(hash["series"])
        stories = StoryList.from_hash(hash["stories"])
        comics = ComicList.from_hash(hash["comics"])
        events = EventList.from_hash(hash["events"])
        # Create object from extracted values
        Creator.new(id,
                    first_name,
                    middle_name,
                    last_name,
                    suffix,
                    full_name,
                    modified,
                    resource_uri,
                    urls,
                    thumbnail,
                    series,
                    stories,
                    comics,
                    events)
      end
    end

    # Defines the key map for json serialization
    def key_map
      hash = {}
      hash['id'] = id
      hash['firstName'] = first_name
      hash['middleName'] = middle_name
      hash['lastName'] = last_name
      hash['suffix'] = suffix
      hash['fullName'] = full_name
      hash['modified'] = modified
      hash['resourceURI'] = resource_uri
      hash['urls'] = urls.map(&:key_map)
      hash['thumbnail'] = thumbnail.key_map
      hash['series'] = series.key_map
      hash['stories'] = stories.key_map
      hash['comics'] = comics.key_map
      hash['events'] = events.key_map
      hash
    end
  end
end
