# This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 05/27/2016

module MarvelComics
  class DateDescriptorEnum
    # TODO: Write general description for this element
    # TODO: Write general description for this element
    # TODO: Write general description for this element
    # TODO: Write general description for this element
    DATE_DESCRIPTOR_ENUM = [LASTWEEK = 'lastWeek', NEXTWEEK = 'nextWeek', THISMONTH = 'thisMonth', THISWEEK = 'thisWeek']
  end
end