# This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 05/27/2016

module MarvelComics
  class FormatTypeEnum
    # TODO: Write general description for this element
    # TODO: Write general description for this element
    FORMAT_TYPE_ENUM = [COLLECTION = 'collection', COMIC = 'comic']
  end
end