# This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 05/27/2016

require 'date'
module MarvelComics
  class Story

    # The unique ID of the story resource.
    # @return [Integer]
    attr_accessor :id

    # The story title.
    # @return [String]
    attr_accessor :title

    # A short description of the story.
    # @return [String]
    attr_accessor :description

    # The canonical URL identifier for this resource.
    # @return [String]
    attr_accessor :resource_uri

    # The story type e.g. interior story, cover, text story.
    # @return [String]
    attr_accessor :type

    # The date the resource was most recently modified.
    # @return [DateTime]
    attr_accessor :modified

    # The representative image for this story.
    # @return [Thumbnail]
    attr_accessor :thumbnail

    # A resource list containing comics in which this story takes place.
    # @return [ComicList]
    attr_accessor :comics

    # A resource list containing series in which this story appears.
    # @return [SeriesList]
    attr_accessor :series

    # A resource list of the events in which this story appears.
    # @return [EventList]
    attr_accessor :events

    # A resource list of characters which appear in this story.
    # @return [CharacterList]
    attr_accessor :characters

    # A resource list of creators who worked on this story.
    # @return [CreatorList]
    attr_accessor :creators

    # A summary representation of the issue in which this story was originally published.
    # @return [ComicSummary]
    attr_accessor :originalissue

    def initialize(id = nil,
                   title = nil,
                   description = nil,
                   resource_uri = nil,
                   type = nil,
                   modified = nil,
                   thumbnail = nil,
                   comics = nil,
                   series = nil,
                   events = nil,
                   characters = nil,
                   creators = nil,
                   originalissue = nil)
      @id = id
      @title = title
      @description = description
      @resource_uri = resource_uri
      @type = type
      @modified = modified
      @thumbnail = thumbnail
      @comics = comics
      @series = series
      @events = events
      @characters = characters
      @creators = creators
      @originalissue = originalissue

    end

    def method_missing(method_name)
      puts "There is no method called '#{method_name}'."
    end

    # Creates JSON of the curent object
    def to_json(options = {})
      hash = key_map
      hash.to_json(options)
    end

    # Creates an instance of the object from a hash
    def self.from_hash(hash)
      if hash == nil
        nil
      else
        # Extract variables from the hash
        id = hash["id"]
        title = hash["title"]
        description = hash["description"]
        resource_uri = hash["resourceURI"]
        type = hash["type"]
        modified = DateTime.iso8601(hash["modified"])
        thumbnail = Thumbnail.from_hash(hash["thumbnail"])
        comics = ComicList.from_hash(hash["comics"])
        series = SeriesList.from_hash(hash["series"])
        events = EventList.from_hash(hash["events"])
        characters = CharacterList.from_hash(hash["characters"])
        creators = CreatorList.from_hash(hash["creators"])
        originalissue = ComicSummary.from_hash(hash["originalissue"])
        # Create object from extracted values
        Story.new(id,
                  title,
                  description,
                  resource_uri,
                  type,
                  modified,
                  thumbnail,
                  comics,
                  series,
                  events,
                  characters,
                  creators,
                  originalissue)
      end
    end

    # Defines the key map for json serialization
    def key_map
      hash = {}
      hash['id'] = id
      hash['title'] = title
      hash['description'] = description
      hash['resourceURI'] = resource_uri
      hash['type'] = type
      hash['modified'] = modified
      hash['thumbnail'] = thumbnail.key_map
      hash['comics'] = comics.key_map
      hash['series'] = series.key_map
      hash['events'] = events.key_map
      hash['characters'] = characters.key_map
      hash['creators'] = creators.key_map
      hash['originalissue'] = originalissue.key_map
      hash
    end
  end
end
