# This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 05/27/2016

module MarvelComics
  class TextObject

    # The canonical type of the text object (e.g. solicit text, preview text, etc.).
    # @return [String]
    attr_accessor :type

    # The IETF language tag denoting the language the text object is written in.
    # @return [String]
    attr_accessor :language

    # The text.
    # @return [String]
    attr_accessor :text

    def initialize(type = nil,
                   language = nil,
                   text = nil)
      @type = type
      @language = language
      @text = text

    end

    def method_missing(method_name)
      puts "There is no method called '#{method_name}'."
    end

    # Creates JSON of the curent object
    def to_json(options = {})
      hash = key_map
      hash.to_json(options)
    end

    # Creates an instance of the object from a hash
    def self.from_hash(hash)
      if hash == nil
        nil
      else
        # Extract variables from the hash
        type = hash["type"]
        language = hash["language"]
        text = hash["text"]
        # Create object from extracted values
        TextObject.new(type,
                       language,
                       text)
      end
    end

    # Defines the key map for json serialization
    def key_map
      hash = {}
      hash['type'] = type
      hash['language'] = language
      hash['text'] = text
      hash
    end
  end
end
