# This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 05/27/2016

module MarvelComics
  class Thumbnail

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :path

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :extension

    def initialize(path = nil,
                   extension = nil)
      @path = path
      @extension = extension

    end

    def method_missing(method_name)
      puts "There is no method called '#{method_name}'."
    end

    # Creates JSON of the curent object
    def to_json(options = {})
      hash = key_map
      hash.to_json(options)
    end

    # Creates an instance of the object from a hash
    def self.from_hash(hash)
      if hash == nil
        nil
      else
        # Extract variables from the hash
        path = hash["path"]
        extension = hash["extension"]
        # Create object from extracted values
        Thumbnail.new(path,
                      extension)
      end
    end

    # Defines the key map for json serialization
    def key_map
      hash = {}
      hash['path'] = path
      hash['extension'] = extension
      hash
    end
  end
end
